# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('avatar', models.CharField(max_length=255, verbose_name='头像')),
                ('summary', models.CharField(max_length=255, verbose_name='简介')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(through='app01.Like', to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='news',
            name='new_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.NewsType', verbose_name='新闻类型'),
        ),
        migrations.AddField(
            model_name='news',
            name='promulgator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p', to='app01.UserInfo', verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='like',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_news', to='app01.News'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_user', to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.News', verbose_name='评论的新闻ID'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='评论者'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'news')]),
        ),
    ]
