# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
